apiVersion: v1
kind: Pod
metadata:
  name: pod-01
  labels:
    env: demo1
spec:
  shareProcessNamespace: true
  containers:
    - name: pod-01
      image: demo/demo:v1
      env:
        - name: CLIENT
          value: "service2"
    - name: mtls
      image: kube-gateway/kube-gateway:v1
      securityContext:
        privileged: true
        #capabilities:
        #  add: ["IPC_LOCK", "SYS_ADMIN", "SYS_RESOURCE", "BPF"]
      volumeMounts:
        - mountPath: /sys/kernel/debug
          name: sys-kernel-debug
        # - name: cgroup
        #   mountPath: /hostfs/sys/fs/cgroup
      env:
        - name: SMESH-CA
          valueFrom:
            secretKeyRef:
              name: pod-01-smesh
              key: ca
        - name: SMESH-CERT
          valueFrom:
            secretKeyRef:
              name: pod-01-smesh
              key: cert
        - name: SMESH-KEY
          valueFrom:
            secretKeyRef:
              name: pod-01-smesh
              key: key
  volumes:
    - name: sys-kernel-debug
      hostPath:
        path: /sys/kernel/debug
        type: DirectoryOrCreate
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-02
  labels:
    env: demo2
spec:
  shareProcessNamespace: true
  containers:
    - name: pod-02
      image: demo/demo:v1
      env:
        - name: CLIENT
          value: "service1"
    - name: mtls
      image: kube-gateway/kube-gateway:v1
      securityContext:
        privileged:
          true
          #capabilities:
          #add: ["IPC_LOCK", "SYS_ADMIN", "SYS_RESOURCE", "BPF"]
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SMESH-CA
          valueFrom:
            secretKeyRef:
              name: pod-02-smesh
              key: ca
        - name: SMESH-CERT
          valueFrom:
            secretKeyRef:
              name: pod-02-smesh
              key: cert
        - name: SMESH-KEY
          valueFrom:
            secretKeyRef:
              name: pod-02-smesh
              key: key
      volumeMounts:
        - mountPath: /sys/kernel/debug
          name: sys-kernel-debug
      #  - name: cgroup
      #    mountPath: /hostfs/sys/fs/cgroup
  volumes:
    - name: sys-kernel-debug
      hostPath:
        path: /sys/kernel/debug
        type: DirectoryOrCreate
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  clusterIP: None # <= Don't forget!!
  selector:
    env: demo1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  clusterIP: None # <= Don't forget!!
  selector:
    env: demo2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
