apiVersion: v1
kind: Namespace
metadata:
  name: sidecar-injector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: sidecar-injector
  name: sidecar-injector
  namespace: sidecar-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: sidecar-injector
  name: sidecar-injector
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: sidecar-injector
  name: sidecar-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidecar-injector
subjects:
- kind: ServiceAccount
  name: sidecar-injector
  namespace: sidecar-injector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sidecar-injector
  name: sidecar-injector
  namespace: sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: sidecar-injector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sidecar-injector
  name: sidecar-injector
  namespace: sidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-injector
  template:
    metadata:
      labels:
        app: sidecar-injector
    spec:
      containers:
      - args:
        - -service-name=sidecar-injector
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: thebsdbox/smesh-controller:v1
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /prestop.sh
        name: sidecar-injector
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 64Mi
      serviceAccountName: sidecar-injector
