kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-injector
  labels:
    app: sidecar-injector
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["create", "delete"]
